runtime: php55
api_version: 1
# Referência em: https://cloud.google.com/appengine/docs/standard/php/config/appref
# Aparentemente, o app.yaml é o novo config.inc.php
error_handlers:
- file: default_error.html

handlers:
#*********************************************************************************#
#                                       CSS                                       #
#*********************************************************************************#
- url: /stylesheets
  static_dir: stylesheets
- url: /pages/stylesheets
  static_dir: pages/stylesheets
- url: /pages/stylesheets/backgrounds
  static_dir: pages/stylesheets/backgrounds
#*********************************************************************************#
#                                   Páginas PHP                                   #
#*********************************************************************************#
# As classes (exemplo.class.php) não precisam ser declaradas aqui!
# Expressão regular para scripts PHP
- url: /(.+)\.php
  script: \1.php
# Home, destino após o login
- url: /pages/home.php
  script: pages/home.php
# Script para iniciar a sessão e tratar login/logout
- url: /pages/loadSession.php
  script: pages/loadSession.php
# Script com a barra do usuário
- url: /pages/userBar.php
  script: pages/userBar.php
# Script com o espaço ativo
- url: /pages/space.php
  script: pages/space.php
# Página intermediária para fazer signout do Fitebase ao perder a sessão
- url: /pages/wayout.php
  script: pages/wayout.php
# AJAX para fechar um espaço
- url: /config/ajax/fecharEspaco.php
  script: config/ajax/fecharEspaco.php
  # AJAX para fazer a busca digitada na barra do usuário
- url: /config/ajax/userBarSearch.php
  script: config/ajax/userBarSearch.php
# Página de teste *****###### TESTE
- url: /pages/testeAjax.php
  script: pages/testeAjax.php
# Página de teste *****###### TESTE
- url: /pages/teste.php
  script: pages/teste.php
# Index
- url: /.*
  script: index.php
#*********************************************************************************#
#                                 Banco de dados                                  #
#*********************************************************************************#
# DEFINIÇÕES DO BANCO DE DADOS TRANFERIDAS PARA: config/loadConn.inc.php
#env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  #MYSQL_DSN: mysql:unix_socket=/cloudsql/le16project:us-central1:le16project-db1;dbname=teste
  #MYSQL_USER: root
  #MYSQL_PASSWORD: a4010b3010c2010d1
